### PR TITLE
refactored tests

### PR DESCRIPTION
**Pull request by mamineahmadi**
### BUD Link
_Link to the bud on Jira_

### Include api paths (if applicable)
_Provide example of api(s) being tested_

### Summary of the PR
Just refactored tests.

### Details
_Mention any extra details_

### Checks
- [x] Tested Changes
- [ ] Ensured that changes do not affect other applications and its use (if applicable)
- [ ] Swagger depicts your api accurately (if applicable)
- [x] Tests are created and working (if applicable)

### CODE REVIEW

**Review by teoPalomino — DISMISSED** [review]
Good job cleaning up these tests!

**Review by MiaMianeko — DISMISSED** [review]
Good job! Correcting small typos is also highly appreciated ☺️

**Review by massimolopez11 — APPROVED** [review]

**Review by teoPalomino — APPROVED** [review]
This code looks clean, thanks for refactoring the tests!

**Review by ThatJustin — APPROVED** [review]
good job

**Pull request merged**
