### PR TITLE
fix(receipts): renable receipt scanner and receipt api

### PR DESCRIPTION
**Pull request by amirsadeghi-ca**
### BUD Link
https://jira.budgetlens.tech/browse/BUD-263

### Include api paths (if applicable)
_Provide example of api(s) being tested_

### Summary of the PR
I renabled Azure and Verifi apis. 

### Details
_Mention any extra details_

### Checks
- [x] Tested Changes
- [ ] Ensured that changes do not affect other applications and its use (if applicable)
- [x] Swagger depicts your api accurately (if applicable)
- [x] Tests are created and working (if applicable)

### CODE REVIEW

**Comment by amirsadeghi-ca** [comment]
> why are you deleting the tests?

those tests were not relevant to the new code, and they are already covered in other tests. so they were unneccessary.

**Comment by mamineahmadi** [comment]
> > why are you deleting the tests?
> 
> those tests were not relevant to the new code, and they are already covered in other tests. so they were unneccessary.

which other tests already cover them?

**Review by mamineahmadi — APPROVED** [review]

**Review by massimolopez11 — APPROVED** [review]
Approved

**Review by teoPalomino — APPROVED** [review]
Worked on this branch, looks good and works well. Good job!

**Pull request merged**
