### PR TITLE
bud-22-Store electronic receipts in the app from my personal email by forwarding the receipts

### PR DESCRIPTION
**Pull request by IsaacMuriuki**
### BUD Link
https://jira.budgetlens.tech/browse/BUD-22

### Include api paths (if applicable)
path('parse/', views.ParseReceiptsAPIView.as_view(), name='parse')

### Summary of the PR
Basically the title

### Details
to test locally send email in format of the default payload in https://docs.sendgrid.com/for-developers/parsing-email/setting-up-the-inbound-parse-webhook and change the "TO" field to the forwarding email of the user you want to test with

### Checks
- [x] Tested Changes
- [ ] Ensured that changes do not affect other applications and its use (if applicable)
- [x] Swagger depicts your api accurately (if applicable)
- [x] Tests are created and working (if applicable)

### CODE REVIEW

**Review by mamineahmadi — CHANGES_REQUESTED** [review]

**Review by mamineahmadi — CHANGES_REQUESTED** [review]
@IsaacMuriuki Please look at the sonarcloud error you have and try to fix the random number logic you used for the forwarding email so it's more secure.

**Comment by mamineahmadi** [comment]
Also, resolve conflicts.

**Review by mamineahmadi — DISMISSED** [review]

**Review by amirsadeghi-ca — DISMISSED** [review]

**Review by mamineahmadi — APPROVED** [review]

**Review by ThatJustin — APPROVED** [review]
Good job. Damn flake8 keeping us down.

**Review by teoPalomino — APPROVED** [review]
The code is clean, seems to work fine on my end.

**Pull request merged**
